### ISSUE TITLE
关于评论区

### ISSUE THREAD

**Issue by smd1121** [CindyZhou2003/mymkdocs#1]
Hello~ 感谢您分享笔记！但是看起来由于您直接使用了我的 mkdocs index.yml 所以您事实上在使用我的评论区 ID：

https://github.com/CindyZhou2003/mymkdocs/blob/gh-pages/index.html#L1290-L1291

并因此影响了我的评论区展示：

<img width="513" alt="image" src="https://github.com/CindyZhou2003/mymkdocs/assets/30610597/ba99d174-feca-4ba1-a0f9-dff8bd22344d">

您可以 follow [官方文档](https://squidfunk.github.io/mkdocs-material/setup/adding-a-comment-system/) 来为自己增添评论系统，需要改的并不多，很方便！

（另外根据我的笔记本的 [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.zh) 和 [SATA](https://github.com/zTrix/sata-license) 协议，您需要在您的笔记本中标明对我代码的引用，并给我点一个 star，谢谢 :)

**Comment by CindyZhou2003** [comment]
学长你好，我是直接使用了您的comments.html，非常抱歉给你造成了困扰，我稍后马上修改一下~
由于不知道应该将您的贡献写在哪里🥺所以将您放在我主页的attribute中了👉👈(将 CC BY-SA 4.0<https://creativecommons.org/licenses/by-sa/4.0/deed.zh> 和 SATA<https://github.com/zTrix/sata-license> 协议也加上了)
如有问题，请再联系我，真的非常抱歉！
________________________________
发件人: 咸鱼暄 ***@***.***>
发送时间: 2024年6月30日 15:17
收件人: CindyZhou2003/mymkdocs ***@***.***>
抄送: Subscribed ***@***.***>
主题: [CindyZhou2003/mymkdocs] 关于评论区 (Issue #1)


Hello~ 感谢您分享笔记！但是看起来由于您直接使用了我的 mkdocs index.yml 所以您事实上在使用我的评论区 ID：

https://github.com/CindyZhou2003/mymkdocs/blob/gh-pages/index.html#L1290-L1291

并因此影响了我的评论区展示：

image.png (view on web)<https://github.com/CindyZhou2003/mymkdocs/assets/30610597/ba99d174-feca-4ba1-a0f9-dff8bd22344d>

您可以 follow 官方文档<https://squidfunk.github.io/mkdocs-material/setup/adding-a-comment-system/> 来为自己增添评论系统，需要改的并不多，很方便！

（另外根据我的笔记本的 CC BY-SA 4.0<https://creativecommons.org/licenses/by-sa/4.0/deed.zh> 和 SATA<https://github.com/zTrix/sata-license> 协议，您需要在您的笔记本中标明对我代码的引用，并给我点一个 star，谢谢 :)

**Comment by smd1121** [comment]
谢谢 🥳 ~ 没关系的我已经找到了哪里删除之前的评论，所以现在已经恢复正常了！
